- name: Manage Ansible inventory in GitHub repository
  hosts: localhost
  gather_facts: no
  vars:
    repo_url: "https://github.com/renejr2006/aws.git"  # No need to include username/token
    repo_name: "aws"
    repo_path: "/tmp/{{ repo_name }}"
    branch: "main"
    inventory_file: "{{ repo_path }}/inventory"
    new_host: "my-new-host ansible_host={{ host_ip }} ansible_user={{ ansible_user }}"

  tasks:
    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ branch }}"
        force: yes
      # AWX will use the linked credential for GitHub authentication