---
- name: Add host to AWX inventory group
  hosts: linux
  tasks:
    - name: Get ID for the group
      uri:
        url: "http://your-awx-server/api/v2/inventory_groups/?inventory={{ inventory_id }}&name=linux"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: group_response

    - name: Add host to the group
      uri:
        url: "http://your-awx-server/api/v2/groups/{{ group_response.json.results[0].id }}/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        body:
          id: "{{ host_id }}"
        body_format: json
        validate_certs: no
      vars:
        host_id: "{{ host_response.json.id }}"
      register: add_host_response

    - name: Get ID for the host
      uri:
        url: "http://your-awx-server/api/v2/hosts/?name=192.168.100.100"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: host_response

    - name: Create new host if not found
      uri:
        url: "http://your-awx-server/api/v2/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        body:
          name: "192.168.100.100"
          description: "New host"
          inventory: "{{ inventory_id }}"
        body_format: json
        validate_certs: no
      register: host_create_response
      when: host_response.json.results | length == 0

    - name: Debug responses
      debug:
        msg:
          - "Group response: {{ group_response }}"
          - "Add host response: {{ add_host_response }}"
          - "Host response: {{ host_response }}"
          - "Host create response: {{ host_create_response }}"