---
- name: Manage Ansible inventory in GitHub repository
  hosts: localhost
  gather_facts: no
  vars:
    repo_url: "https://github.com/renejr2006/aws.git"  # Your GitHub repository URL
    repo_name: "aws"
    repo_path: "/tmp/{{ repo_name }}"
    branch: "main"
    new_host: "my-new-host ansible_host={{ host_ip }} ansible_user={{ ansible_user }}"
    
    # Set these values as needed for your inventory
    host_ip: "192.168.1.50"  # Replace with the actual IP of the new host
    ansible_user: "admin"    # Replace with the actual user for the new host

  tasks:
    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ branch }}"
        force: yes
      # The Source Control credential in AWX will be used for GitHub authentication

    - name: Ensure the inventory file exists in the repo
      stat:
        path: "{{ repo_path }}/inventory"
      register: inventory_file_check

    - name: Fail if no inventory file is found in the repository
      fail:
        msg: "No inventory file found in the repository!"
      when: not inventory_file_check.stat.exists

    - name: Add new host entry to the inventory file
      lineinfile:
        path: "{{ repo_path }}/inventory"
        line: "{{ new_host }}"
        insertafter: "[my_hosts]"  # Adjust this based on your inventory file structure
      register: inventory_update

    - name: Commit changes if the inventory was updated
      command: "git commit -am 'Added {{ new_host }} to inventory'"
      args:
        chdir: "{{ repo_path }}"
      when: inventory_update.changed

    - name: Push the changes to the GitHub repository
      command: "git push origin {{ branch }}"
      args:
        chdir: "{{ repo_path }}"
      when: inventory_update.changed

    - name: Display a message if the new host was added
      debug:
        msg: "Host {{ new_host }} added to the inventory."
      when: inventory_update.changed