---
- name: Add a new host to the inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add new host entry to the inventory file
      lineinfile:
        path: "/etc/ansible/hosts"      # Path to your inventory file
        line: "{{ new_host }}"
        insertafter: "[my_hosts]"       # Add host under this group
      vars:
        new_host: "my-new-host ansible_host={{ host_ip }} ansible_user={{ ansible_user }}"

    - name: Display the newly added host
      debug:
        msg: "Host {{ new_host }} added to the inventory."