---
- name: Register a host in the 'linux' group
  hosts: linux
  gather_facts: no

  tasks:
    - name: Add the host to the linux group in the inventory
      add_host:
        name: "vol"
        groups: "Systems Lab"

    - name: Display registered host
      debug:
        msg: "Host {{ system_name }} has been added to the linux group."