---
- name: IP
  hosts: linux
  gather_facts: true
  become: yes
  vars:
    runtime: 1440  # Default runtime in minutes, can be overridden by --extra-vars

  tasks:
    - name: Capture start time
      ansible.builtin.command: date +%s
      register: start_time

    - name: Run FHC test with dynamic runtime
      ansible.builtin.shell: |
        PATH=/usr/local/bin:/usr/bin:/bin ./run-fhc.sh {{ runtime }}
      args:
        chdir: /tmp/fhc
      register: script_output
      ignore_errors: no
      environment:
        TERM: "xterm"

    - name: Capture end time
      ansible.builtin.command: date +%s
      register: end_time

    - name: Calculate actual runtime
      ansible.builtin.set_fact:
        actual_runtime: "{{ end_time.stdout | int - start_time.stdout | int }}"

    - name: Convert runtime to seconds
      ansible.builtin.set_fact:
        expected_runtime_seconds: "{{ runtime | int * 60 }}"

    - name: Fail if runtime is less than expected
      ansible.builtin.fail:
        msg: >
          Test failed. Actual runtime was {{ actual_runtime }} seconds, which is less than the expected runtime of {{ expected_runtime_seconds }} seconds ({{ runtime }} minutes).
      when: actual_runtime < expected_runtime_seconds

    - name: Output success message if runtime was as expected
      ansible.builtin.debug:
        msg: "The test completed successfully. Actual runtime: {{ actual_runtime }} seconds."
      when: actual_runtime >= expected_runtime_seconds
