---
- name: IP
  hosts: linux
  gather_facts: True
  become: yes
  #vars_files:
  #   - all.yml
  tasks:
    - name: Downloading stressng
      command: >
        wget -N ftp://10.230.136.14/Public/Rene/tests/sat.tar.xz -O /tmp/sat.tar.xz
        
    - name: Gave chmod +x to tar.xz 
      ansible.builtin.file:
        path: /tmp/sat.tar.xz
        mode: '0755'
        state: file

    - name: Extracting tar.xz
      ansible.builtin.unarchive:
        src: /tmp/sat.tar.xz
        dest: /tmp/
        remote_src: yes

#---------------------------------------------------
#---------------------------------------------------
    - name: Run ins
      ansible.builtin.command:
        cmd: /tmp/sat/install-sat-ubu.sh
      args:
        chdir: /tmp/sat/
        
    - name: Run run-sat
      ansible.builtin.command:
        cmd: /tmp/sat/run-sat.sh 86400 cmp
      args:
        chdir: /tmp/sat
        ignore_errors: yes
