---
- name: Capture UTC and Local Time
  hosts: linux
  tasks:
    - name: Get UTC Time
      ansible.builtin.command:
        cmd: date -u +"%Y-%m-%d %H:%M:%S"
      register: utc_time

    - name: Get current Local Time
      ansible.builtin.command:
        cmd: date +"%Y_%m-%d %H:%M:%S"
      register: local_time_24hr

    - name: Convert Local Time to 12-hr format with AM/PM
      ansible.builtin.command:
        cmd: date +"%Y_%m-%d %I:%M %p"
      register: local_time_12hr

    - name: Display UTC Time
      ansible.builtin.debug:
        msg: "Current UTC time is {{ utc_time.stdout }}"

    - name: Display Local Time
      ansible.builtin.debug:
        msg: "Current Local Time is {{ local_time_12hr.stdout }}"
