---
- name: Show dmesg
  hosts: linux
  become: true
  tasks:
    - name: Run dmesg command
      shell:  stdbuf -oL -eL dmesg -T | egrep -ivw default | egrep -i 'bert|mce|mca|error|lockup|fault' 2>&1
      register: dmesg_output
      changed_when: false

    - name: Display dmesg output
      ansible.builtin.debug: 
        msg: "{{ dmesg_output.stdout_lines  }}"
