---
- name: Updating System
  hosts: linux
  become: yes
  tasks:
    - name: Running Update and upgrades
      shell: apt-get update && apt-get upgrade -y
      register: upgrade_output

    - name: Display Update & Upgrade Output
      debug:
        msg: "{{ item  }}"
      with_items: "{{ upgrade_output.stdout_lines }}"
