---
- name: Reboot Server
  hosts: linux
  become: yes
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 300
      register: reboot_result

    - name: Waiting for server to become reachable again
      wait_for_connection:
        delay: 10
        timeout: 300
      when: reboot_result.changed
